apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aap

resources:
  - pvc.yml
  - schedule-job.yml

configMapGenerator:
  - name: aap-restore-backup
    files:
      - backup.sh

generatorOptions:
  disableNameSuffixHash: true
