kind: AutomationController
apiVersion: automationcontroller.ansible.com/v1beta1
metadata:
  namespace: aap
  name: automation-controller
spec:
  postgres_configuration_secret: aap-db-connection
  # postgres_extra_args:
  # - '-c'
  # - 'shared_preload_libraries=pgaudit'
  # - '-c'
  # - 'pgaudit.log=all'