apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: aap-db
spec:
  instances: 3

  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: aap
      owner: aap-user
      secret:
        name: aap-db-secret

  # Require 1Gi of space
  storage:
    size: 1Gi