apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
spec:
  generators:
  - list:
      elements:
      # - name: aap-operator
      #   path: apps/aap-operator/2.4
      #   namespace: aap
      #   syncWave: "5"
      - name: aap-external-db
        path: apps/cloud-native-pg-ressources/test-cluster
        namespace: aap-db
        syncWave: "5"
      - name: aap-backup
        path: apps/aap-restore/test-cluster
        namespace: aap-db
        syncWave: "5"
      - name: aap-operator
        path: apps/aap-operator/2.6
        namespace: aap
        syncWave: "6"
      - name: aap-instance
        path: apps/aap-resources/2.6/test-cluster
        namespace: aap
        syncWave: "6"